name: Deploy Spring Boot to EC2 (Ubuntu)

on:
  push:
    branches:
      - main  # Ejecutar el workflow cuando hagas push a la rama main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout del código fuente
      - name: Checkout source code
        uses: actions/checkout@v2

      # 2️⃣ Configurar Java 21 y construir el archivo .war
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: temurin

      - name: Build with Maven
        run: mvn clean package

      # 3️⃣ Copiar el .war al servidor EC2
      - name: Copy .war to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: 54.205.253.120
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: target/demo-0.0.1-SNAPSHOT.war
          target: /home/ubuntu/demo.war

      # 4️⃣ Mover el archivo .war a la ubicación de Tomcat y ajustar permisos
      - name: Move .war to Tomcat directory and set permissions
        uses: appleboy/ssh-action@master
        with:
          host: 54.205.253.120
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}  # Añadir la clave privada para SSH
          script: |
              sudo mv /home/ubuntu/demo.war /var/lib/tomcat10/webapps/demo.war
              sudo chown tomcat:tomcat /var/lib/tomcat10/webapps/demo.war
              sudo chmod 755 /var/lib/tomcat10/webapps/demo.war
      # 5️⃣ Reiniciar Tomcat
      - name: Restart Tomcat
        uses: appleboy/ssh-action@master
        with:
          host: 54.205.253.120
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo systemctl restart tomcat10

